name: AI Reviewer
description: Comment from AI

# GitHub Marketplace - Branding (Optional)
branding:
  icon: "terminal"
  color: "black"

# Input params
inputs:
  GOOGLE_API_KEY:
    description: "Google AI Studio API Key"

# Action steps - used in client workflow scenario
runs:
  using: "composite"
  steps:
    - name: Run action
      run: node ${GITHUB_ACTION_PATH}/dist/use-reviewer.js
      shell: bash
      env:
        GOOGLE_API_KEY: ${{ inputs.GOOGLE_API_KEY }}
